<a href="https://colab.research.google.com/github/mabimaalfata/Ai/blob/main/JST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#! pip install keras
#Remove '#' in above line if not installed keras
import keras
import numpy as np
from sklearn.datasets import load_iris
dataset=load_iris()
#How data looks likes?
print (dataset)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [ ]:
#Step : 1 : know the data
print(type(dataset))
print(len(dataset))
#Dataset is in bunch format. bunch is a dictionary like object.
print(dataset.keys())
#We try to find out what values are stored in these attributes
print(dataset['data'][0:5])
print(dataset['target'][0:5])
print(dataset['target_names'][0:5])
print(dataset['DESCR'])
print(dataset['feature_names'])
print(dataset['filename'])
#next we difine our x and y; y isthe dependent on x
x=dataset['data']
print(len(x)) #To check length of dataset
y=dataset['target']
print(len(y)) #To check length of dataset
print(x[0])
print(y[0])

<class 'sklearn.utils._bunch.Bunch'>
8
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
['setosa' 'versicolor' 'virginica']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ==============

In [ ]:
#Step : 2 : Convert y into one hot encoded vector
#One hot encoding is used because Y has labels (0,1,2)- which is a categorical categorical data whit no ordinal relationship
from keras.utils import to_categorical
Ny=len(np.unique(y))
print(Ny)
Y=to_categorical(y,num_classes=Ny)
print(Y[0:5])

3
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [ ]:
#Step3 : 3 : Now we split the data into two parts - one for training another for testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.10,shuffle=True)
print(x_train[0:5])
print(x_test[0:5])
print(y_train[0:5])
print(y_test[0:5])


[[5.1 3.8 1.9 0.4]
 [5.1 3.8 1.5 0.3]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.3 3.7 1.5 0.2]]
[[5.8 2.8 5.1 2.4]
 [6.5 3.2 5.1 2. ]
 [5.4 3.  4.5 1.5]
 [5.4 3.4 1.7 0.2]
 [4.8 3.4 1.9 0.2]]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [ ]:
#Step : 4 : Then we normalize the data
from sklearn.preprocessing import StandardScaler
#Normalization is done so that the difference betwen highets and lowest data point is not too large
import numpy as np
scaler=StandardScaler()
#To find mean and std dev
scaler.fit(x_train)

#Conveting data into from where mean of data is 0 and std dev is 1
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
print(np.amax(x_train,axis=0))
print(np.amin(x_train,axis=0))


[2.3269833  3.16567093 1.81519089 1.73547842]
[-1.91313316 -2.0345739  -1.56679635 -1.44672309]


In [ ]:
#step : 5 : Now finally we bulid the model using keras
!pip install tensorflow
import keras
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(20, input_dim=x_train.shape[1], activation='relu'))
#Dropout is used to avoid overfitting
keras.layers.Dropout(0.2)
model.add(Dense(20, activation='relu'))
keras.layers.Dropout(0.2)
model.add(Dense(20, activation='relu'))
keras.layers.Dropout(0.2)
#For classification problems, we usually use softmax as activition function function in final layey
model.add(Dense(3, activation='softmax'))
#Compiling the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#Step : 6 : know model
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 20)                100       
                                                                 
 dense_1 (Dense)             (None, 20)                420       
                                                                 
 dense_2 (Dense)             (None, 20)                420       
                                                                 
 dense_3 (Dense)             (None, 3)                 63        
                                                                 
Total params: 1,003
Trainable params: 1,003
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#Step : 7 : train the model
#Bath sixe,ec[ocs and validation split are all hyper parameters
model.fit(x_train, y_train, epochs=195, batch_size=80, validation_split=0.1)

Epoch 1/195
2/2 [==============================] - 1s 292ms/step - loss: 1.1156 - accuracy: 0.1488 - val_loss: 1.1315 - val_accuracy: 0.0714
Epoch 2/195
2/2 [==============================] - 0s 56ms/step - loss: 1.0996 - accuracy: 0.2149 - val_loss: 1.1167 - val_accuracy: 0.2143
Epoch 3/195
2/2 [==============================] - 0s 35ms/step - loss: 1.0835 - accuracy: 0.3719 - val_loss: 1.1013 - val_accuracy: 0.3571
Epoch 4/195
2/2 [==============================] - 0s 58ms/step - loss: 1.0677 - accuracy: 0.5207 - val_loss: 1.0862 - val_accuracy: 0.4286
Epoch 5/195
2/2 [==============================] - 0s 37ms/step - loss: 1.0520 - accuracy: 0.5537 - val_loss: 1.0716 - val_accuracy: 0.5000
Epoch 6/195
2/2 [==============================] - 0s 35ms/step - loss: 1.0365 - accuracy: 0.6281 - val_loss: 1.0579 - val_accuracy: 0.6429
Epoch 7/195
2/2 [==============================] - 0s 33ms/step - loss: 1.0215 - accuracy: 0.6529 - val_loss: 1.0446 - val_accuracy: 0.6429
Epoch 8/195
2/2 [==

In [ ]:
#Step : 8 : Get  the accuracy of model on testing data
testing=model.evaluate(x_test, y_test)
print("\n%s: %.2f%%" %(model.metrics_names[1]+'uracy of model on testing data',testing[1]*100))

1/1 [==============================] - 0s 30ms/step - loss: 0.1149 - accuracy: 0.9333

accuracyuracy of model on testing data: 93.33%


In [ ]:
#Step : 9 : Evaluate our model
from sklearn.metrics import classification_report, confusion_matrix
predictions = np.argmax(model.predict(x_test), axis=1)
y_test = np.argmax(y_test,axis=1)
#To get confusion matrix
print (confusion_matrix(y_test,predictions))
#To get values of all evaluation metrics)
print(classification_report(y_test,predictions))

1/1 [==============================] - 0s 38ms/step


AxisError: ignored